### ISSUE TITLE
Syllabus responds to both trailing-slash and non-trailing-slash versions of pages, but links only work on one or the other

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/syllabus#121]
If you go to https://syllabus.codeyourfuture.io/git/index the links (like to the preparation page) work.

If you go to https://syllabus.codeyourfuture.io/git/index/ they don't

We should force the server to redirect one to the another, to be canonical, and make sure the links work on that version.

**Comment by ChrisOwen101** [comment]
@illicitonion The first one re-directs to the second one for me. 

What browser are you using?

**Comment by illicitonion** [comment]
Interesting, they do _now_ for me, but I swear (and @ClaireBickley [reported](https://codeyourfuture.slack.com/archives/C01DANTAGRK/p1604140873000300) it wasn't working before... Weird.

Anywho, looks like links are _always_ broken now, so we should fix that!

**Comment by ClaireBickley** [comment]
Still not working for me :(

Latest Google Chrome
Version 86.0.4240.183 (Official Build) (64-bit)

![Screenshot 2020-11-04 113854](https://user-images.githubusercontent.com/58375712/98107375-5d0b1d00-1e92-11eb-92bc-a48585eff65f.jpg)

**Comment by illicitonion** [comment]
## Problem diagnosis

Ok, this looks like it's a bug around links within Docusausrus pages?

If you go to https://syllabus.codeyourfuture.io/git/overview/ the link to "Week 1" is a link to `https://syllabus.codeyourfuture.io/git/index`

If you click it, it _doesn't_ follow the 301 to `https://syllabus.codeyourfuture.io/git/index/`, it just takes you straight to `https://syllabus.codeyourfuture.io/git/index`. I guess it's doing a fancy pushState transition rather than a full GET?

## What we should do

I _think_ we should be writing the pages assuming the 301 is followed, so we need to change the link on index to be to `../preparation` rather than `preparation`. This doesn't sit fantastically with me, as I view `/index` and `/preparation` as pages rather than folders, but if we have the 301 in place, it's what we should do.

But for this to work, we need to _also_ either:
1. Fix link in docusaurus in general so that the 301s are actually followed
2. Change every place that we link to `/git/index` to instead be a link to `/git/index/` - this feels error-prone, and is kind of sad.

**Comment by ChrisOwen101** [comment]
@ClaireBickley Isn't the issue that the page that you're trying to visit doesn't exist?

You're trying to go to 

https://syllabus.codeyourfuture.io/git/index/preparation

which is not a page. Where did you click to get that url from?

**Comment by ChrisOwen101** [comment]
Seems to be a known issue in Docusaurus

https://github.com/facebook/docusaurus/issues/3372
